### ISSUE TITLE
Hello, can ros2 branch be used for testing now？

### ISSUE THREAD

**Issue by Allen070206** [javieryu/nerf_bridge#19]
Hi.
I noticed that you are currently working on the ros2 branch, can it work as well as the main branch？

**Comment by javieryu** [comment]
It's all still an experimental branch, but you can use it for testing from this https://github.com/javieryu/nerf_bridge/commit/db866ba2756aac0bc60b06fbb11b1864d07f4ac1 commit. I believe that's what has worked for previous people.

**Comment by Allen070206** [comment]
Thank you for your quick reply，I think I'll use the main branch first, and I'll test the ros2 branch later  :)
