### ISSUE TITLE
Checkpoints are not being saved

### ISSUE THREAD

**Issue by bharath-k1000** [javieryu/nerf_bridge#20]
Hi,
While config.yml files are created in the correct locations, checkpoints are not being saved. Training is running fine but cannot view previous runs.
![image](https://github.com/javieryu/nerf_bridge/assets/86649903/43ed3ae4-2226-42f1-9cca-d28841222c05)

The nerfstudio_models directory is not being created.

Any help would be appreciated!
thank you!

**Comment by javieryu** [comment]
Right now we don't save any checkpoints. I'd recommend forking the code to add this feature. PRs are also welcome!

**Comment by javieryu** [comment]
Closing this!
