### ISSUE TITLE
Hello!Is the ORB-SLAM3 algorithm currently available on the ROS 2-based NerfBridge?

### ISSUE THREAD

**Issue by Allen070206** [javieryu/nerf_bridge#33]
<img width="487" alt="9392001b474d9dc0adc25e211afc31e" src="https://github.com/javieryu/nerf_bridge/assets/31239123/fada418b-1721-4143-a16c-d758ff102646">
From the code, I noticed your comment. Currently, if I use the ORB-SLAM3 algorithm, do I need to modify the code?

**Comment by javieryu** [comment]
I haven't actually tried using any of the ORBSLAM3 ROS2 packages -- although I know a couple exist. If you get them working then you shouldn't need to modify any of the code, just pass in a new ``slam_method`` string. The ``slam_method`` string is used to indicate which coordinate convention is used to define the rotation of the camera in the slam frame. You'll just have to double check the coordinate frame of the Odometry messages, and choose the appropriate ``slam_method`` that way. Eventually I'd like to make that whole convention system more transparent, but until then you're welcome to just post in this thread and I will try to help you where I can!

**Comment by javieryu** [comment]
Closing this for now, but feel free to reopen if you have more trouble.
