### ISSUE TITLE
Error Encountered in ros-depth-splatfacto Due to Changes in gsplat Package Behavior

### ISSUE THREAD

**Issue by MarvinChung** [javieryu/nerf_bridge#34]
Hi, thank you for your great work! 

While utilizing the ros-depth-splatfacto, I encountered an issue triggered by the latest gsplat package when executing the following command:

```
ns-train ros-depth-splatfacto --data configs/desk.json --pipeline.datamanager.use-compressed-rgb True --pipeline.datamanager.dataparser.scene-scale-factor 0.5 --pipeline.datamanager.data-update-freq 8.0
```
This resulted in the following error:
```
AssertionError: block_width must be between 2 and 16
```
This error has been addressed in the [issue raised on the gsplat GitHub repository](https://github.com/nerfstudio-project/gsplat/issues/159), indicating changes in the code behavior.

The solution is to modify the installation command from:
```
pip install git+https://github.com/nerfstudio-project/gsplat.git
```
to
```
pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.6
```
as documented in the last line of [Installation section 4](https://github.com/javieryu/nerf_bridge/blob/main/README.md#installation-1).

**Comment by MarvinChung** [comment]
The rendered output from ros-depth-splatfacto is significantly inferior to that of ros-depth-nerfacto. Do you have any insights into the possible causes behind this discrepancy? I'm keen to investigate this issue further.

**Comment by javieryu** [comment]
Hi! Something that I've noticed recently is that gaussian splatting seems to be more sensitive to camera pose errors. I would recommend installing nerfstudio from source and using the camera pose optimizer SO3xR3 is the one I've tried and it seems to help a bit!
