### ISSUE TITLE
ROS Bag?

### ISSUE THREAD

**Issue by CharlieRusso001** [javieryu/nerf_bridge#35]
When trying to install the ROS bag file to test the build of this repo on my machine the python file provided ends up creating a .db3 file is there a simple way around this or is there any other place to download a ROS bag.

Thanks

**Comment by javieryu** [comment]
ROS2 bags are directories with a .db3 database and a meta data file.

**Comment by CharlieRusso001** [comment]
Ok, thanks I have had more experience with ROS1 and those have an actual ros bag file I am relatively new to using ROS2 thanks.
