### ISSUE TITLE
Rendering Results

### ISSUE THREAD

**Issue by Augusthyq** [javieryu/nerf_bridge#38]
Thank you for your good job! I have two questions: 
     1)  When I run orbslam3 calling nerfstudio, only two image frames are displayed, but it seems to be able to render the approximate scene. Is this normal?     

     2) Can the intrinsic parameters provided by the dataset be copied directly into the JSON file?
Thank you very much if you can help answer.

**Comment by Augusthyq** [comment]
> Thank you for your good job! I have two questions: 1) When I run orbslam3 calling nerfstudio, only two image frames are displayed, but it seems to be able to render the approximate scene. Is this normal?
> 
> ```
>  2) Can the intrinsic parameters provided by the dataset be copied directly into the JSON file?
> ```
> 
> Thank you very much if you can help answer.

![Uploading 123.png…]()

**Comment by Augusthyq** [comment]
> Thank you for your good job! I have two questions: 1) When I run orbslam3 calling nerfstudio, only two image frames are displayed, but it seems to be able to render the approximate scene. Is this normal?
> 
> ```
>  2) Can the intrinsic parameters provided by the dataset be copied directly into the JSON file?
> ```
> 
> Thank you very much if you can help answer.

![123](https://github.com/javieryu/nerf_bridge/assets/74721580/f66c88cb-9b58-4de7-89de-b96438bf0492)

**Comment by javieryu** [comment]
1) Looks like you are using the ROS1 version of NerfBridge. This uses the old Nerfstudio viewer which was unstable, and did not always show all of the poses. From the looks of your TUM results I think you have more than just two images, and sometimes refreshing the page can show the new images (although this is buggy and does not always work).

2) Yes, you can use the camera calibration from the dataset. Just copy the correct values into the JSON.

**Comment by Augusthyq** [comment]
Thank you very much for your reply.
